-- Generated by tools/generate_pack.py

function ff7_pool_200000()
    return ff7_location_in_pool(200000) and 1 or 0
end

function ff7_pool_200001()
    return ff7_location_in_pool(200001) and 1 or 0
end

function ff7_pool_200002()
    return ff7_location_in_pool(200002) and 1 or 0
end

function ff7_pool_200003()
    return ff7_location_in_pool(200003) and 1 or 0
end

function ff7_pool_200004()
    return ff7_location_in_pool(200004) and 1 or 0
end

function ff7_pool_200005()
    return ff7_location_in_pool(200005) and 1 or 0
end

function ff7_pool_200006()
    return ff7_location_in_pool(200006) and 1 or 0
end

function ff7_pool_200007()
    return ff7_location_in_pool(200007) and 1 or 0
end

function ff7_pool_200008()
    return ff7_location_in_pool(200008) and 1 or 0
end

function ff7_pool_200009()
    return ff7_location_in_pool(200009) and 1 or 0
end

function ff7_pool_200010()
    return ff7_location_in_pool(200010) and 1 or 0
end

function ff7_pool_200011()
    return ff7_location_in_pool(200011) and 1 or 0
end

function ff7_pool_200012()
    return ff7_location_in_pool(200012) and 1 or 0
end

function ff7_pool_200013()
    return ff7_location_in_pool(200013) and 1 or 0
end

function ff7_pool_200014()
    return ff7_location_in_pool(200014) and 1 or 0
end

function ff7_pool_200015()
    return ff7_location_in_pool(200015) and 1 or 0
end

function ff7_pool_200016()
    return ff7_location_in_pool(200016) and 1 or 0
end

function ff7_pool_200017()
    return ff7_location_in_pool(200017) and 1 or 0
end

function ff7_pool_200018()
    return ff7_location_in_pool(200018) and 1 or 0
end

function ff7_pool_200019()
    return ff7_location_in_pool(200019) and 1 or 0
end

function ff7_pool_200021()
    return ff7_location_in_pool(200021) and 1 or 0
end

function ff7_pool_200024()
    return ff7_location_in_pool(200024) and 1 or 0
end

function ff7_pool_200025()
    return ff7_location_in_pool(200025) and 1 or 0
end

function ff7_pool_200026()
    return ff7_location_in_pool(200026) and 1 or 0
end

function ff7_pool_200027()
    return ff7_location_in_pool(200027) and 1 or 0
end

function ff7_pool_200028()
    return ff7_location_in_pool(200028) and 1 or 0
end

function ff7_pool_200029()
    return ff7_location_in_pool(200029) and 1 or 0
end

function ff7_pool_200125()
    return ff7_location_in_pool(200125) and 1 or 0
end

function ff7_pool_200135()
    return ff7_location_in_pool(200135) and 1 or 0
end

function ff7_pool_200183()
    return ff7_location_in_pool(200183) and 1 or 0
end

function ff7_pool_200184()
    return ff7_location_in_pool(200184) and 1 or 0
end

function ff7_pool_200266()
    return ff7_location_in_pool(200266) and 1 or 0
end

function ff7_pool_200267()
    return ff7_location_in_pool(200267) and 1 or 0
end

function ff7_pool_200280()
    return ff7_location_in_pool(200280) and 1 or 0
end

function ff7_pool_200281()
    return ff7_location_in_pool(200281) and 1 or 0
end

function ff7_pool_200285()
    return ff7_location_in_pool(200285) and 1 or 0
end

function ff7_pool_200286()
    return ff7_location_in_pool(200286) and 1 or 0
end

function ff7_pool_200287()
    return ff7_location_in_pool(200287) and 1 or 0
end

function ff7_pool_200288()
    return ff7_location_in_pool(200288) and 1 or 0
end

function ff7_pool_200289()
    return ff7_location_in_pool(200289) and 1 or 0
end

function ff7_pool_200290()
    return ff7_location_in_pool(200290) and 1 or 0
end

function ff7_pool_200291()
    return ff7_location_in_pool(200291) and 1 or 0
end

function ff7_pool_200292()
    return ff7_location_in_pool(200292) and 1 or 0
end

function ff7_pool_200293()
    return ff7_location_in_pool(200293) and 1 or 0
end

function ff7_pool_200294()
    return ff7_location_in_pool(200294) and 1 or 0
end

function ff7_pool_200295()
    return ff7_location_in_pool(200295) and 1 or 0
end

function ff7_pool_200296()
    return ff7_location_in_pool(200296) and 1 or 0
end

function ff7_pool_200297()
    return ff7_location_in_pool(200297) and 1 or 0
end

function ff7_pool_200298()
    return ff7_location_in_pool(200298) and 1 or 0
end

function ff7_pool_200299()
    return ff7_location_in_pool(200299) and 1 or 0
end

function ff7_pool_200300()
    return ff7_location_in_pool(200300) and 1 or 0
end

function ff7_pool_200301()
    return ff7_location_in_pool(200301) and 1 or 0
end

function ff7_pool_200302()
    return ff7_location_in_pool(200302) and 1 or 0
end

function ff7_pool_200304()
    return ff7_location_in_pool(200304) and 1 or 0
end

function ff7_pool_200305()
    return ff7_location_in_pool(200305) and 1 or 0
end

function ff7_pool_200306()
    return ff7_location_in_pool(200306) and 1 or 0
end

function ff7_pool_200307()
    return ff7_location_in_pool(200307) and 1 or 0
end

function ff7_pool_200308()
    return ff7_location_in_pool(200308) and 1 or 0
end

function ff7_pool_200309()
    return ff7_location_in_pool(200309) and 1 or 0
end

function ff7_pool_200310()
    return ff7_location_in_pool(200310) and 1 or 0
end

function ff7_pool_200311()
    return ff7_location_in_pool(200311) and 1 or 0
end

function ff7_pool_200313()
    return ff7_location_in_pool(200313) and 1 or 0
end

function ff7_pool_200314()
    return ff7_location_in_pool(200314) and 1 or 0
end

function ff7_pool_200315()
    return ff7_location_in_pool(200315) and 1 or 0
end

function ff7_pool_200316()
    return ff7_location_in_pool(200316) and 1 or 0
end

function ff7_pool_200317()
    return ff7_location_in_pool(200317) and 1 or 0
end

function ff7_pool_200318()
    return ff7_location_in_pool(200318) and 1 or 0
end

function ff7_pool_200319()
    return ff7_location_in_pool(200319) and 1 or 0
end

function ff7_pool_200320()
    return ff7_location_in_pool(200320) and 1 or 0
end

function ff7_pool_200321()
    return ff7_location_in_pool(200321) and 1 or 0
end

function ff7_pool_200322()
    return ff7_location_in_pool(200322) and 1 or 0
end

function ff7_pool_200323()
    return ff7_location_in_pool(200323) and 1 or 0
end

function ff7_pool_200324()
    return ff7_location_in_pool(200324) and 1 or 0
end

function ff7_pool_200325()
    return ff7_location_in_pool(200325) and 1 or 0
end

function ff7_pool_200326()
    return ff7_location_in_pool(200326) and 1 or 0
end

function ff7_pool_200327()
    return ff7_location_in_pool(200327) and 1 or 0
end

function ff7_pool_200328()
    return ff7_location_in_pool(200328) and 1 or 0
end

function ff7_pool_200329()
    return ff7_location_in_pool(200329) and 1 or 0
end

function ff7_pool_200330()
    return ff7_location_in_pool(200330) and 1 or 0
end

function ff7_pool_200331()
    return ff7_location_in_pool(200331) and 1 or 0
end

function ff7_pool_200332()
    return ff7_location_in_pool(200332) and 1 or 0
end

function ff7_pool_200333()
    return ff7_location_in_pool(200333) and 1 or 0
end

function ff7_pool_200334()
    return ff7_location_in_pool(200334) and 1 or 0
end

function ff7_pool_200335()
    return ff7_location_in_pool(200335) and 1 or 0
end

function ff7_pool_200336()
    return ff7_location_in_pool(200336) and 1 or 0
end

function ff7_pool_200337()
    return ff7_location_in_pool(200337) and 1 or 0
end

function ff7_pool_200338()
    return ff7_location_in_pool(200338) and 1 or 0
end

function ff7_pool_200339()
    return ff7_location_in_pool(200339) and 1 or 0
end

function ff7_pool_200340()
    return ff7_location_in_pool(200340) and 1 or 0
end

function ff7_pool_200341()
    return ff7_location_in_pool(200341) and 1 or 0
end

function ff7_pool_200342()
    return ff7_location_in_pool(200342) and 1 or 0
end

function ff7_pool_200343()
    return ff7_location_in_pool(200343) and 1 or 0
end

function ff7_pool_200344()
    return ff7_location_in_pool(200344) and 1 or 0
end

function ff7_pool_200345()
    return ff7_location_in_pool(200345) and 1 or 0
end

function ff7_pool_200346()
    return ff7_location_in_pool(200346) and 1 or 0
end

function ff7_pool_200347()
    return ff7_location_in_pool(200347) and 1 or 0
end

function ff7_pool_200348()
    return ff7_location_in_pool(200348) and 1 or 0
end

function ff7_pool_200349()
    return ff7_location_in_pool(200349) and 1 or 0
end

function ff7_pool_200350()
    return ff7_location_in_pool(200350) and 1 or 0
end

function ff7_pool_200351()
    return ff7_location_in_pool(200351) and 1 or 0
end

function ff7_pool_200352()
    return ff7_location_in_pool(200352) and 1 or 0
end

function ff7_pool_200353()
    return ff7_location_in_pool(200353) and 1 or 0
end

function ff7_pool_200354()
    return ff7_location_in_pool(200354) and 1 or 0
end

function ff7_pool_200355()
    return ff7_location_in_pool(200355) and 1 or 0
end

function ff7_pool_200356()
    return ff7_location_in_pool(200356) and 1 or 0
end

function ff7_pool_200357()
    return ff7_location_in_pool(200357) and 1 or 0
end

function ff7_pool_200358()
    return ff7_location_in_pool(200358) and 1 or 0
end

function ff7_pool_200359()
    return ff7_location_in_pool(200359) and 1 or 0
end

function ff7_pool_200360()
    return ff7_location_in_pool(200360) and 1 or 0
end

function ff7_pool_200361()
    return ff7_location_in_pool(200361) and 1 or 0
end

function ff7_pool_200362()
    return ff7_location_in_pool(200362) and 1 or 0
end

function ff7_pool_200363()
    return ff7_location_in_pool(200363) and 1 or 0
end

function ff7_pool_200364()
    return ff7_location_in_pool(200364) and 1 or 0
end

function ff7_pool_200365()
    return ff7_location_in_pool(200365) and 1 or 0
end

function ff7_pool_200367()
    return ff7_location_in_pool(200367) and 1 or 0
end

function ff7_pool_200368()
    return ff7_location_in_pool(200368) and 1 or 0
end

function ff7_pool_200369()
    return ff7_location_in_pool(200369) and 1 or 0
end

function ff7_pool_200370()
    return ff7_location_in_pool(200370) and 1 or 0
end

function ff7_pool_200371()
    return ff7_location_in_pool(200371) and 1 or 0
end

function ff7_pool_200372()
    return ff7_location_in_pool(200372) and 1 or 0
end

function ff7_pool_300000()
    return ff7_location_in_pool(300000) and 1 or 0
end

function ff7_pool_300001()
    return ff7_location_in_pool(300001) and 1 or 0
end

function ff7_pool_300003()
    return ff7_location_in_pool(300003) and 1 or 0
end

function ff7_pool_300004()
    return ff7_location_in_pool(300004) and 1 or 0
end

function ff7_pool_300005()
    return ff7_location_in_pool(300005) and 1 or 0
end

function ff7_pool_300006()
    return ff7_location_in_pool(300006) and 1 or 0
end

function ff7_pool_300007()
    return ff7_location_in_pool(300007) and 1 or 0
end

function ff7_pool_300008()
    return ff7_location_in_pool(300008) and 1 or 0
end

function ff7_pool_300011()
    return ff7_location_in_pool(300011) and 1 or 0
end

function ff7_pool_300012()
    return ff7_location_in_pool(300012) and 1 or 0
end

function ff7_pool_300013()
    return ff7_location_in_pool(300013) and 1 or 0
end

function ff7_pool_300014()
    return ff7_location_in_pool(300014) and 1 or 0
end

function ff7_pool_300016()
    return ff7_location_in_pool(300016) and 1 or 0
end

function ff7_pool_300017()
    return ff7_location_in_pool(300017) and 1 or 0
end

function ff7_pool_300018()
    return ff7_location_in_pool(300018) and 1 or 0
end

function ff7_pool_300022()
    return ff7_location_in_pool(300022) and 1 or 0
end

function ff7_pool_300029()
    return ff7_location_in_pool(300029) and 1 or 0
end

function ff7_pool_300030()
    return ff7_location_in_pool(300030) and 1 or 0
end

function ff7_pool_300031()
    return ff7_location_in_pool(300031) and 1 or 0
end

function ff7_pool_300032()
    return ff7_location_in_pool(300032) and 1 or 0
end

function ff7_pool_300038()
    return ff7_location_in_pool(300038) and 1 or 0
end

function ff7_pool_300040()
    return ff7_location_in_pool(300040) and 1 or 0
end

function ff7_pool_300041()
    return ff7_location_in_pool(300041) and 1 or 0
end

function ff7_pool_300043()
    return ff7_location_in_pool(300043) and 1 or 0
end

function ff7_pool_300046()
    return ff7_location_in_pool(300046) and 1 or 0
end

function ff7_pool_300047()
    return ff7_location_in_pool(300047) and 1 or 0
end

function ff7_pool_300055()
    return ff7_location_in_pool(300055) and 1 or 0
end

function ff7_pool_300062()
    return ff7_location_in_pool(300062) and 1 or 0
end

function ff7_pool_300063()
    return ff7_location_in_pool(300063) and 1 or 0
end

function ff7_pool_300064()
    return ff7_location_in_pool(300064) and 1 or 0
end

function ff7_pool_300065()
    return ff7_location_in_pool(300065) and 1 or 0
end

function ff7_pool_300066()
    return ff7_location_in_pool(300066) and 1 or 0
end

function ff7_pool_300068()
    return ff7_location_in_pool(300068) and 1 or 0
end

function ff7_pool_300069()
    return ff7_location_in_pool(300069) and 1 or 0
end

function ff7_pool_300070()
    return ff7_location_in_pool(300070) and 1 or 0
end

function ff7_pool_300071()
    return ff7_location_in_pool(300071) and 1 or 0
end

function ff7_pool_300073()
    return ff7_location_in_pool(300073) and 1 or 0
end

function ff7_pool_300074()
    return ff7_location_in_pool(300074) and 1 or 0
end

function ff7_pool_300075()
    return ff7_location_in_pool(300075) and 1 or 0
end

function ff7_pool_300077()
    return ff7_location_in_pool(300077) and 1 or 0
end

function ff7_pool_300078()
    return ff7_location_in_pool(300078) and 1 or 0
end

function ff7_pool_300079()
    return ff7_location_in_pool(300079) and 1 or 0
end

function ff7_pool_300080()
    return ff7_location_in_pool(300080) and 1 or 0
end

function ff7_pool_300081()
    return ff7_location_in_pool(300081) and 1 or 0
end

function ff7_pool_300082()
    return ff7_location_in_pool(300082) and 1 or 0
end

function ff7_pool_300084()
    return ff7_location_in_pool(300084) and 1 or 0
end

function ff7_pool_300089()
    return ff7_location_in_pool(300089) and 1 or 0
end

function ff7_pool_300090()
    return ff7_location_in_pool(300090) and 1 or 0
end

function ff7_pool_300100()
    return ff7_location_in_pool(300100) and 1 or 0
end

function ff7_pool_300104()
    return ff7_location_in_pool(300104) and 1 or 0
end

function ff7_pool_300109()
    return ff7_location_in_pool(300109) and 1 or 0
end

function ff7_pool_300111()
    return ff7_location_in_pool(300111) and 1 or 0
end

function ff7_pool_300113()
    return ff7_location_in_pool(300113) and 1 or 0
end

function ff7_pool_300114()
    return ff7_location_in_pool(300114) and 1 or 0
end

function ff7_pool_300115()
    return ff7_location_in_pool(300115) and 1 or 0
end

function ff7_pool_300116()
    return ff7_location_in_pool(300116) and 1 or 0
end

function ff7_pool_300117()
    return ff7_location_in_pool(300117) and 1 or 0
end

function ff7_pool_300119()
    return ff7_location_in_pool(300119) and 1 or 0
end

function ff7_pool_300120()
    return ff7_location_in_pool(300120) and 1 or 0
end

function ff7_pool_300121()
    return ff7_location_in_pool(300121) and 1 or 0
end

function ff7_pool_300122()
    return ff7_location_in_pool(300122) and 1 or 0
end

function ff7_pool_300124()
    return ff7_location_in_pool(300124) and 1 or 0
end

function ff7_pool_300128()
    return ff7_location_in_pool(300128) and 1 or 0
end

function ff7_pool_300129()
    return ff7_location_in_pool(300129) and 1 or 0
end

function ff7_pool_300130()
    return ff7_location_in_pool(300130) and 1 or 0
end

function ff7_pool_300131()
    return ff7_location_in_pool(300131) and 1 or 0
end

function ff7_pool_300132()
    return ff7_location_in_pool(300132) and 1 or 0
end

function ff7_pool_300133()
    return ff7_location_in_pool(300133) and 1 or 0
end

function ff7_pool_300151()
    return ff7_location_in_pool(300151) and 1 or 0
end

function ff7_pool_300152()
    return ff7_location_in_pool(300152) and 1 or 0
end

function ff7_pool_300153()
    return ff7_location_in_pool(300153) and 1 or 0
end

function ff7_pool_300155()
    return ff7_location_in_pool(300155) and 1 or 0
end

function ff7_pool_300156()
    return ff7_location_in_pool(300156) and 1 or 0
end

function ff7_pool_300160()
    return ff7_location_in_pool(300160) and 1 or 0
end

function ff7_pool_300161()
    return ff7_location_in_pool(300161) and 1 or 0
end

function ff7_pool_300163()
    return ff7_location_in_pool(300163) and 1 or 0
end

function ff7_pool_300165()
    return ff7_location_in_pool(300165) and 1 or 0
end

function ff7_pool_300169()
    return ff7_location_in_pool(300169) and 1 or 0
end

function ff7_pool_300170()
    return ff7_location_in_pool(300170) and 1 or 0
end

function ff7_pool_300172()
    return ff7_location_in_pool(300172) and 1 or 0
end

function ff7_pool_300174()
    return ff7_location_in_pool(300174) and 1 or 0
end

function ff7_pool_300175()
    return ff7_location_in_pool(300175) and 1 or 0
end

function ff7_pool_300177()
    return ff7_location_in_pool(300177) and 1 or 0
end

function ff7_pool_300179()
    return ff7_location_in_pool(300179) and 1 or 0
end

function ff7_pool_300180()
    return ff7_location_in_pool(300180) and 1 or 0
end

function ff7_pool_300182()
    return ff7_location_in_pool(300182) and 1 or 0
end

function ff7_pool_300183()
    return ff7_location_in_pool(300183) and 1 or 0
end

function ff7_pool_300184()
    return ff7_location_in_pool(300184) and 1 or 0
end

function ff7_pool_300186()
    return ff7_location_in_pool(300186) and 1 or 0
end

function ff7_pool_300187()
    return ff7_location_in_pool(300187) and 1 or 0
end

function ff7_pool_300189()
    return ff7_location_in_pool(300189) and 1 or 0
end

function ff7_pool_300190()
    return ff7_location_in_pool(300190) and 1 or 0
end

function ff7_pool_300191()
    return ff7_location_in_pool(300191) and 1 or 0
end

function ff7_pool_300193()
    return ff7_location_in_pool(300193) and 1 or 0
end

function ff7_pool_300196()
    return ff7_location_in_pool(300196) and 1 or 0
end

function ff7_pool_300197()
    return ff7_location_in_pool(300197) and 1 or 0
end

function ff7_pool_300198()
    return ff7_location_in_pool(300198) and 1 or 0
end

function ff7_pool_300199()
    return ff7_location_in_pool(300199) and 1 or 0
end

function ff7_pool_300208()
    return ff7_location_in_pool(300208) and 1 or 0
end

function ff7_pool_300209()
    return ff7_location_in_pool(300209) and 1 or 0
end

function ff7_pool_300214()
    return ff7_location_in_pool(300214) and 1 or 0
end

function ff7_pool_300215()
    return ff7_location_in_pool(300215) and 1 or 0
end

function ff7_pool_300216()
    return ff7_location_in_pool(300216) and 1 or 0
end

function ff7_pool_300217()
    return ff7_location_in_pool(300217) and 1 or 0
end

function ff7_pool_300218()
    return ff7_location_in_pool(300218) and 1 or 0
end

function ff7_pool_300219()
    return ff7_location_in_pool(300219) and 1 or 0
end

function ff7_pool_300220()
    return ff7_location_in_pool(300220) and 1 or 0
end

function ff7_pool_300221()
    return ff7_location_in_pool(300221) and 1 or 0
end

function ff7_pool_300224()
    return ff7_location_in_pool(300224) and 1 or 0
end

function ff7_pool_300225()
    return ff7_location_in_pool(300225) and 1 or 0
end

function ff7_pool_300226()
    return ff7_location_in_pool(300226) and 1 or 0
end

function ff7_pool_300228()
    return ff7_location_in_pool(300228) and 1 or 0
end

function ff7_pool_300229()
    return ff7_location_in_pool(300229) and 1 or 0
end

function ff7_pool_300230()
    return ff7_location_in_pool(300230) and 1 or 0
end

function ff7_pool_300231()
    return ff7_location_in_pool(300231) and 1 or 0
end

function ff7_pool_300232()
    return ff7_location_in_pool(300232) and 1 or 0
end

function ff7_pool_300233()
    return ff7_location_in_pool(300233) and 1 or 0
end

function ff7_pool_300234()
    return ff7_location_in_pool(300234) and 1 or 0
end

function ff7_pool_300235()
    return ff7_location_in_pool(300235) and 1 or 0
end

function ff7_pool_300237()
    return ff7_location_in_pool(300237) and 1 or 0
end

function ff7_pool_300239()
    return ff7_location_in_pool(300239) and 1 or 0
end

function ff7_pool_300240()
    return ff7_location_in_pool(300240) and 1 or 0
end

function ff7_pool_300241()
    return ff7_location_in_pool(300241) and 1 or 0
end

function ff7_pool_300248()
    return ff7_location_in_pool(300248) and 1 or 0
end

function ff7_pool_300249()
    return ff7_location_in_pool(300249) and 1 or 0
end

function ff7_pool_300250()
    return ff7_location_in_pool(300250) and 1 or 0
end

function ff7_pool_300259()
    return ff7_location_in_pool(300259) and 1 or 0
end

function ff7_pool_300260()
    return ff7_location_in_pool(300260) and 1 or 0
end

function ff7_pool_300265()
    return ff7_location_in_pool(300265) and 1 or 0
end

function ff7_pool_300269()
    return ff7_location_in_pool(300269) and 1 or 0
end

function ff7_pool_300270()
    return ff7_location_in_pool(300270) and 1 or 0
end

function ff7_pool_300271()
    return ff7_location_in_pool(300271) and 1 or 0
end

function ff7_pool_300272()
    return ff7_location_in_pool(300272) and 1 or 0
end

function ff7_pool_300274()
    return ff7_location_in_pool(300274) and 1 or 0
end

function ff7_pool_300275()
    return ff7_location_in_pool(300275) and 1 or 0
end

function ff7_pool_300281()
    return ff7_location_in_pool(300281) and 1 or 0
end

function ff7_pool_300284()
    return ff7_location_in_pool(300284) and 1 or 0
end

function ff7_pool_300285()
    return ff7_location_in_pool(300285) and 1 or 0
end

function ff7_pool_300286()
    return ff7_location_in_pool(300286) and 1 or 0
end

function ff7_pool_300287()
    return ff7_location_in_pool(300287) and 1 or 0
end

function ff7_pool_300289()
    return ff7_location_in_pool(300289) and 1 or 0
end

function ff7_pool_300290()
    return ff7_location_in_pool(300290) and 1 or 0
end

function ff7_pool_300297()
    return ff7_location_in_pool(300297) and 1 or 0
end

function ff7_pool_300313()
    return ff7_location_in_pool(300313) and 1 or 0
end

function ff7_pool_300321()
    return ff7_location_in_pool(300321) and 1 or 0
end

function ff7_pool_300322()
    return ff7_location_in_pool(300322) and 1 or 0
end

function ff7_pool_300346()
    return ff7_location_in_pool(300346) and 1 or 0
end

function ff7_pool_300361()
    return ff7_location_in_pool(300361) and 1 or 0
end

function ff7_pool_300362()
    return ff7_location_in_pool(300362) and 1 or 0
end

function ff7_pool_300363()
    return ff7_location_in_pool(300363) and 1 or 0
end

function ff7_pool_300364()
    return ff7_location_in_pool(300364) and 1 or 0
end

function ff7_pool_300365()
    return ff7_location_in_pool(300365) and 1 or 0
end

function ff7_pool_300366()
    return ff7_location_in_pool(300366) and 1 or 0
end

function ff7_pool_300367()
    return ff7_location_in_pool(300367) and 1 or 0
end

function ff7_pool_300368()
    return ff7_location_in_pool(300368) and 1 or 0
end

function ff7_pool_300369()
    return ff7_location_in_pool(300369) and 1 or 0
end

function ff7_pool_300370()
    return ff7_location_in_pool(300370) and 1 or 0
end

function ff7_pool_300371()
    return ff7_location_in_pool(300371) and 1 or 0
end

function ff7_pool_300386()
    return ff7_location_in_pool(300386) and 1 or 0
end

function ff7_pool_300387()
    return ff7_location_in_pool(300387) and 1 or 0
end

function ff7_pool_300390()
    return ff7_location_in_pool(300390) and 1 or 0
end

function ff7_pool_300391()
    return ff7_location_in_pool(300391) and 1 or 0
end

function ff7_pool_300398()
    return ff7_location_in_pool(300398) and 1 or 0
end

function ff7_pool_300438()
    return ff7_location_in_pool(300438) and 1 or 0
end

function ff7_pool_300439()
    return ff7_location_in_pool(300439) and 1 or 0
end

function ff7_pool_310000()
    return ff7_location_in_pool(310000) and 1 or 0
end

function ff7_pool_310001()
    return ff7_location_in_pool(310001) and 1 or 0
end

function ff7_pool_310002()
    return ff7_location_in_pool(310002) and 1 or 0
end

function ff7_pool_310003()
    return ff7_location_in_pool(310003) and 1 or 0
end

function ff7_pool_310004()
    return ff7_location_in_pool(310004) and 1 or 0
end

function ff7_pool_310005()
    return ff7_location_in_pool(310005) and 1 or 0
end

function ff7_pool_310006()
    return ff7_location_in_pool(310006) and 1 or 0
end

function ff7_pool_310007()
    return ff7_location_in_pool(310007) and 1 or 0
end

function ff7_pool_310008()
    return ff7_location_in_pool(310008) and 1 or 0
end

function ff7_pool_310009()
    return ff7_location_in_pool(310009) and 1 or 0
end

function ff7_pool_310010()
    return ff7_location_in_pool(310010) and 1 or 0
end

function ff7_pool_310011()
    return ff7_location_in_pool(310011) and 1 or 0
end

function ff7_pool_310012()
    return ff7_location_in_pool(310012) and 1 or 0
end

function ff7_pool_310013()
    return ff7_location_in_pool(310013) and 1 or 0
end

function ff7_pool_310014()
    return ff7_location_in_pool(310014) and 1 or 0
end

function ff7_pool_310015()
    return ff7_location_in_pool(310015) and 1 or 0
end

function ff7_pool_310016()
    return ff7_location_in_pool(310016) and 1 or 0
end

function ff7_pool_310017()
    return ff7_location_in_pool(310017) and 1 or 0
end

function ff7_pool_310018()
    return ff7_location_in_pool(310018) and 1 or 0
end

function ff7_pool_310019()
    return ff7_location_in_pool(310019) and 1 or 0
end

function ff7_pool_310020()
    return ff7_location_in_pool(310020) and 1 or 0
end

function ff7_pool_310021()
    return ff7_location_in_pool(310021) and 1 or 0
end

function ff7_pool_310022()
    return ff7_location_in_pool(310022) and 1 or 0
end

function ff7_pool_310023()
    return ff7_location_in_pool(310023) and 1 or 0
end

function ff7_pool_310024()
    return ff7_location_in_pool(310024) and 1 or 0
end

function ff7_pool_310025()
    return ff7_location_in_pool(310025) and 1 or 0
end

function ff7_pool_310026()
    return ff7_location_in_pool(310026) and 1 or 0
end

function ff7_pool_310027()
    return ff7_location_in_pool(310027) and 1 or 0
end

function ff7_pool_310028()
    return ff7_location_in_pool(310028) and 1 or 0
end

function ff7_pool_310029()
    return ff7_location_in_pool(310029) and 1 or 0
end

function ff7_pool_310030()
    return ff7_location_in_pool(310030) and 1 or 0
end

function ff7_pool_310031()
    return ff7_location_in_pool(310031) and 1 or 0
end

function ff7_pool_310032()
    return ff7_location_in_pool(310032) and 1 or 0
end

function ff7_pool_310033()
    return ff7_location_in_pool(310033) and 1 or 0
end

function ff7_pool_310034()
    return ff7_location_in_pool(310034) and 1 or 0
end

function ff7_pool_310035()
    return ff7_location_in_pool(310035) and 1 or 0
end

function ff7_pool_310036()
    return ff7_location_in_pool(310036) and 1 or 0
end

function ff7_pool_310037()
    return ff7_location_in_pool(310037) and 1 or 0
end

function ff7_pool_310038()
    return ff7_location_in_pool(310038) and 1 or 0
end

function ff7_pool_310039()
    return ff7_location_in_pool(310039) and 1 or 0
end

function ff7_pool_310040()
    return ff7_location_in_pool(310040) and 1 or 0
end

function ff7_pool_310041()
    return ff7_location_in_pool(310041) and 1 or 0
end

function ff7_pool_310042()
    return ff7_location_in_pool(310042) and 1 or 0
end

function ff7_pool_310043()
    return ff7_location_in_pool(310043) and 1 or 0
end

function ff7_pool_310044()
    return ff7_location_in_pool(310044) and 1 or 0
end

function ff7_pool_310045()
    return ff7_location_in_pool(310045) and 1 or 0
end

function ff7_pool_310046()
    return ff7_location_in_pool(310046) and 1 or 0
end

function ff7_pool_310047()
    return ff7_location_in_pool(310047) and 1 or 0
end

function ff7_pool_310048()
    return ff7_location_in_pool(310048) and 1 or 0
end

function ff7_pool_310049()
    return ff7_location_in_pool(310049) and 1 or 0
end

function ff7_pool_310050()
    return ff7_location_in_pool(310050) and 1 or 0
end

function ff7_pool_310051()
    return ff7_location_in_pool(310051) and 1 or 0
end

function ff7_pool_310052()
    return ff7_location_in_pool(310052) and 1 or 0
end

function ff7_pool_310053()
    return ff7_location_in_pool(310053) and 1 or 0
end

function ff7_pool_310054()
    return ff7_location_in_pool(310054) and 1 or 0
end

function ff7_pool_310055()
    return ff7_location_in_pool(310055) and 1 or 0
end

function ff7_pool_310056()
    return ff7_location_in_pool(310056) and 1 or 0
end

function ff7_pool_310057()
    return ff7_location_in_pool(310057) and 1 or 0
end

function ff7_pool_310058()
    return ff7_location_in_pool(310058) and 1 or 0
end

function ff7_pool_310059()
    return ff7_location_in_pool(310059) and 1 or 0
end

function ff7_pool_310060()
    return ff7_location_in_pool(310060) and 1 or 0
end

function ff7_pool_310061()
    return ff7_location_in_pool(310061) and 1 or 0
end

function ff7_pool_310062()
    return ff7_location_in_pool(310062) and 1 or 0
end

function ff7_pool_310063()
    return ff7_location_in_pool(310063) and 1 or 0
end

function ff7_pool_310064()
    return ff7_location_in_pool(310064) and 1 or 0
end

function ff7_pool_310065()
    return ff7_location_in_pool(310065) and 1 or 0
end

function ff7_pool_310066()
    return ff7_location_in_pool(310066) and 1 or 0
end

function ff7_pool_310067()
    return ff7_location_in_pool(310067) and 1 or 0
end

function ff7_pool_310068()
    return ff7_location_in_pool(310068) and 1 or 0
end

function ff7_pool_310069()
    return ff7_location_in_pool(310069) and 1 or 0
end

function ff7_pool_310070()
    return ff7_location_in_pool(310070) and 1 or 0
end

function ff7_pool_310071()
    return ff7_location_in_pool(310071) and 1 or 0
end

function ff7_pool_310072()
    return ff7_location_in_pool(310072) and 1 or 0
end

function ff7_pool_310073()
    return ff7_location_in_pool(310073) and 1 or 0
end

function ff7_pool_310074()
    return ff7_location_in_pool(310074) and 1 or 0
end

function ff7_pool_310075()
    return ff7_location_in_pool(310075) and 1 or 0
end

function ff7_pool_310076()
    return ff7_location_in_pool(310076) and 1 or 0
end

function ff7_pool_310077()
    return ff7_location_in_pool(310077) and 1 or 0
end

function ff7_pool_310078()
    return ff7_location_in_pool(310078) and 1 or 0
end

function ff7_pool_310079()
    return ff7_location_in_pool(310079) and 1 or 0
end

function ff7_pool_310080()
    return ff7_location_in_pool(310080) and 1 or 0
end

function ff7_pool_310081()
    return ff7_location_in_pool(310081) and 1 or 0
end

function ff7_pool_310082()
    return ff7_location_in_pool(310082) and 1 or 0
end

function ff7_pool_310083()
    return ff7_location_in_pool(310083) and 1 or 0
end

function ff7_pool_310084()
    return ff7_location_in_pool(310084) and 1 or 0
end

function ff7_pool_310085()
    return ff7_location_in_pool(310085) and 1 or 0
end

function ff7_pool_310086()
    return ff7_location_in_pool(310086) and 1 or 0
end

function ff7_pool_310087()
    return ff7_location_in_pool(310087) and 1 or 0
end

function ff7_pool_310088()
    return ff7_location_in_pool(310088) and 1 or 0
end

function ff7_pool_310089()
    return ff7_location_in_pool(310089) and 1 or 0
end

function ff7_pool_310090()
    return ff7_location_in_pool(310090) and 1 or 0
end

function ff7_pool_310091()
    return ff7_location_in_pool(310091) and 1 or 0
end

function ff7_pool_310092()
    return ff7_location_in_pool(310092) and 1 or 0
end

function ff7_pool_310093()
    return ff7_location_in_pool(310093) and 1 or 0
end

function ff7_pool_310094()
    return ff7_location_in_pool(310094) and 1 or 0
end

function ff7_pool_310095()
    return ff7_location_in_pool(310095) and 1 or 0
end

function ff7_pool_310096()
    return ff7_location_in_pool(310096) and 1 or 0
end

function ff7_pool_320000()
    return ff7_location_in_pool(320000) and 1 or 0
end

function ff7_pool_320001()
    return ff7_location_in_pool(320001) and 1 or 0
end

function ff7_pool_320002()
    return ff7_location_in_pool(320002) and 1 or 0
end

function ff7_pool_320003()
    return ff7_location_in_pool(320003) and 1 or 0
end

function ff7_pool_320004()
    return ff7_location_in_pool(320004) and 1 or 0
end

function ff7_pool_320005()
    return ff7_location_in_pool(320005) and 1 or 0
end

function ff7_pool_320006()
    return ff7_location_in_pool(320006) and 1 or 0
end

function ff7_pool_320007()
    return ff7_location_in_pool(320007) and 1 or 0
end

function ff7_pool_320008()
    return ff7_location_in_pool(320008) and 1 or 0
end

function ff7_pool_320009()
    return ff7_location_in_pool(320009) and 1 or 0
end

function ff7_pool_320010()
    return ff7_location_in_pool(320010) and 1 or 0
end

function ff7_pool_320011()
    return ff7_location_in_pool(320011) and 1 or 0
end

function ff7_pool_320012()
    return ff7_location_in_pool(320012) and 1 or 0
end

function ff7_pool_320013()
    return ff7_location_in_pool(320013) and 1 or 0
end

function ff7_pool_320014()
    return ff7_location_in_pool(320014) and 1 or 0
end

function ff7_pool_320015()
    return ff7_location_in_pool(320015) and 1 or 0
end

function ff7_pool_320016()
    return ff7_location_in_pool(320016) and 1 or 0
end

function ff7_pool_320017()
    return ff7_location_in_pool(320017) and 1 or 0
end

function ff7_pool_320018()
    return ff7_location_in_pool(320018) and 1 or 0
end

function ff7_pool_320019()
    return ff7_location_in_pool(320019) and 1 or 0
end

function ff7_pool_320020()
    return ff7_location_in_pool(320020) and 1 or 0
end

function ff7_pool_320021()
    return ff7_location_in_pool(320021) and 1 or 0
end

function ff7_pool_320022()
    return ff7_location_in_pool(320022) and 1 or 0
end

function ff7_pool_320023()
    return ff7_location_in_pool(320023) and 1 or 0
end

function ff7_pool_320024()
    return ff7_location_in_pool(320024) and 1 or 0
end

function ff7_pool_320025()
    return ff7_location_in_pool(320025) and 1 or 0
end

function ff7_pool_320026()
    return ff7_location_in_pool(320026) and 1 or 0
end

function ff7_pool_320027()
    return ff7_location_in_pool(320027) and 1 or 0
end

function ff7_pool_320028()
    return ff7_location_in_pool(320028) and 1 or 0
end

function ff7_pool_320029()
    return ff7_location_in_pool(320029) and 1 or 0
end

function ff7_pool_320030()
    return ff7_location_in_pool(320030) and 1 or 0
end

function ff7_pool_320031()
    return ff7_location_in_pool(320031) and 1 or 0
end

function ff7_pool_320032()
    return ff7_location_in_pool(320032) and 1 or 0
end

function ff7_pool_320033()
    return ff7_location_in_pool(320033) and 1 or 0
end

function ff7_pool_320034()
    return ff7_location_in_pool(320034) and 1 or 0
end

function ff7_pool_320035()
    return ff7_location_in_pool(320035) and 1 or 0
end

function ff7_pool_320036()
    return ff7_location_in_pool(320036) and 1 or 0
end

function ff7_pool_320037()
    return ff7_location_in_pool(320037) and 1 or 0
end

function ff7_pool_320038()
    return ff7_location_in_pool(320038) and 1 or 0
end

function ff7_pool_320039()
    return ff7_location_in_pool(320039) and 1 or 0
end

function ff7_pool_320040()
    return ff7_location_in_pool(320040) and 1 or 0
end

function ff7_pool_320041()
    return ff7_location_in_pool(320041) and 1 or 0
end

function ff7_pool_320042()
    return ff7_location_in_pool(320042) and 1 or 0
end

function ff7_pool_320043()
    return ff7_location_in_pool(320043) and 1 or 0
end

function ff7_pool_320044()
    return ff7_location_in_pool(320044) and 1 or 0
end

function ff7_pool_320045()
    return ff7_location_in_pool(320045) and 1 or 0
end

function ff7_pool_320046()
    return ff7_location_in_pool(320046) and 1 or 0
end

function ff7_pool_320047()
    return ff7_location_in_pool(320047) and 1 or 0
end

function ff7_pool_320048()
    return ff7_location_in_pool(320048) and 1 or 0
end

function ff7_pool_320049()
    return ff7_location_in_pool(320049) and 1 or 0
end

function ff7_pool_320050()
    return ff7_location_in_pool(320050) and 1 or 0
end

function ff7_pool_320051()
    return ff7_location_in_pool(320051) and 1 or 0
end

function ff7_pool_320052()
    return ff7_location_in_pool(320052) and 1 or 0
end

function ff7_pool_320053()
    return ff7_location_in_pool(320053) and 1 or 0
end

function ff7_pool_320054()
    return ff7_location_in_pool(320054) and 1 or 0
end

function ff7_pool_320055()
    return ff7_location_in_pool(320055) and 1 or 0
end

function ff7_pool_320056()
    return ff7_location_in_pool(320056) and 1 or 0
end

function ff7_pool_320057()
    return ff7_location_in_pool(320057) and 1 or 0
end

function ff7_pool_320058()
    return ff7_location_in_pool(320058) and 1 or 0
end

function ff7_pool_320059()
    return ff7_location_in_pool(320059) and 1 or 0
end

function ff7_pool_320060()
    return ff7_location_in_pool(320060) and 1 or 0
end

function ff7_pool_320061()
    return ff7_location_in_pool(320061) and 1 or 0
end

function ff7_pool_320062()
    return ff7_location_in_pool(320062) and 1 or 0
end

function ff7_pool_320063()
    return ff7_location_in_pool(320063) and 1 or 0
end

function ff7_pool_320064()
    return ff7_location_in_pool(320064) and 1 or 0
end

function ff7_pool_320065()
    return ff7_location_in_pool(320065) and 1 or 0
end

function ff7_pool_320066()
    return ff7_location_in_pool(320066) and 1 or 0
end

function ff7_pool_320067()
    return ff7_location_in_pool(320067) and 1 or 0
end

function ff7_pool_320068()
    return ff7_location_in_pool(320068) and 1 or 0
end

function ff7_pool_320069()
    return ff7_location_in_pool(320069) and 1 or 0
end

function ff7_pool_320070()
    return ff7_location_in_pool(320070) and 1 or 0
end

function ff7_pool_320071()
    return ff7_location_in_pool(320071) and 1 or 0
end

function ff7_pool_320072()
    return ff7_location_in_pool(320072) and 1 or 0
end

function ff7_pool_320073()
    return ff7_location_in_pool(320073) and 1 or 0
end

function ff7_pool_320074()
    return ff7_location_in_pool(320074) and 1 or 0
end

function ff7_pool_320075()
    return ff7_location_in_pool(320075) and 1 or 0
end

function ff7_pool_320076()
    return ff7_location_in_pool(320076) and 1 or 0
end

function ff7_pool_320077()
    return ff7_location_in_pool(320077) and 1 or 0
end

function ff7_pool_320078()
    return ff7_location_in_pool(320078) and 1 or 0
end

function ff7_pool_320079()
    return ff7_location_in_pool(320079) and 1 or 0
end

function ff7_pool_320080()
    return ff7_location_in_pool(320080) and 1 or 0
end

function ff7_pool_320081()
    return ff7_location_in_pool(320081) and 1 or 0
end

function ff7_pool_320082()
    return ff7_location_in_pool(320082) and 1 or 0
end

function ff7_pool_320083()
    return ff7_location_in_pool(320083) and 1 or 0
end

function ff7_pool_320084()
    return ff7_location_in_pool(320084) and 1 or 0
end

function ff7_pool_320085()
    return ff7_location_in_pool(320085) and 1 or 0
end

function ff7_pool_320086()
    return ff7_location_in_pool(320086) and 1 or 0
end

function ff7_pool_320087()
    return ff7_location_in_pool(320087) and 1 or 0
end

function ff7_pool_320088()
    return ff7_location_in_pool(320088) and 1 or 0
end

function ff7_pool_320089()
    return ff7_location_in_pool(320089) and 1 or 0
end

function ff7_pool_320090()
    return ff7_location_in_pool(320090) and 1 or 0
end

function ff7_pool_320091()
    return ff7_location_in_pool(320091) and 1 or 0
end

function ff7_pool_320092()
    return ff7_location_in_pool(320092) and 1 or 0
end

function ff7_pool_320093()
    return ff7_location_in_pool(320093) and 1 or 0
end

function ff7_pool_320094()
    return ff7_location_in_pool(320094) and 1 or 0
end

function ff7_pool_320095()
    return ff7_location_in_pool(320095) and 1 or 0
end

function ff7_pool_320096()
    return ff7_location_in_pool(320096) and 1 or 0
end

function ff7_pool_320097()
    return ff7_location_in_pool(320097) and 1 or 0
end

function ff7_pool_320098()
    return ff7_location_in_pool(320098) and 1 or 0
end

function ff7_pool_320099()
    return ff7_location_in_pool(320099) and 1 or 0
end

function ff7_pool_320100()
    return ff7_location_in_pool(320100) and 1 or 0
end

function ff7_pool_320101()
    return ff7_location_in_pool(320101) and 1 or 0
end

function ff7_pool_320102()
    return ff7_location_in_pool(320102) and 1 or 0
end

function ff7_pool_320103()
    return ff7_location_in_pool(320103) and 1 or 0
end

function ff7_pool_320104()
    return ff7_location_in_pool(320104) and 1 or 0
end

function ff7_pool_320105()
    return ff7_location_in_pool(320105) and 1 or 0
end

function ff7_pool_320106()
    return ff7_location_in_pool(320106) and 1 or 0
end

function ff7_pool_320107()
    return ff7_location_in_pool(320107) and 1 or 0
end

function ff7_pool_320108()
    return ff7_location_in_pool(320108) and 1 or 0
end

function ff7_pool_320109()
    return ff7_location_in_pool(320109) and 1 or 0
end

function ff7_pool_320110()
    return ff7_location_in_pool(320110) and 1 or 0
end

function ff7_pool_320111()
    return ff7_location_in_pool(320111) and 1 or 0
end

function ff7_pool_320112()
    return ff7_location_in_pool(320112) and 1 or 0
end

function ff7_pool_320113()
    return ff7_location_in_pool(320113) and 1 or 0
end

function ff7_pool_320114()
    return ff7_location_in_pool(320114) and 1 or 0
end

function ff7_pool_320116()
    return ff7_location_in_pool(320116) and 1 or 0
end
