-- Generated by tools/generate_pack.py

function ff7_has_item_100527()
    return ff7_has_key_item('item_100527') and 1 or 0
end

function ff7_has_item_100528()
    return ff7_has_key_item('item_100528') and 1 or 0
end

function ff7_has_item_100537()
    return ff7_has_key_item('item_100537') and 1 or 0
end

function ff7_has_item_100540()
    return ff7_has_key_item('item_100540') and 1 or 0
end

function ff7_has_item_100546()
    return ff7_has_key_item('item_100546') and 1 or 0
end

function ff7_has_item_300503()
    return ff7_has_key_item('item_300503') and 1 or 0
end
