"""Extract slot-data-related constants from the FF7 APWorld."""

from __future__ import annotations

import re
from pathlib import Path

GOLD_SAUCER_REGIONS = (
    "Gold Saucer Area",
    "Shops - Gold Saucer Area",
)

WEAPON_BOSS_NAMES = (
    "Defeat Ultimate Weapon",
    "Defeat Emerald Weapon",
    "Defeat Ruby Weapon",
)


def _parse_frozenset(apworld_init: str, name: str) -> set[int]:
    match = re.search(rf"{name}\s*=\s*frozenset\(\{{(.*?)\}}\)", apworld_init, re.S)
    if not match:
        raise RuntimeError(f"Could not parse {name} from __init__.py")
    body = match.group(1)
  # Match AP location/shop codes only (ignore years like 2026 in comments).
    return {int(value) for value in re.findall(r"\b(?:[23]\d{5}|32\d{4})\b", body)}


def load_slot_constants(apworld: Path) -> dict[str, object]:
    init_text = (apworld / "__init__.py").read_text(encoding="utf-8")
    locations = __import__("json").loads((apworld / "data" / "locations.json").read_text(encoding="utf-8"))
    name_to_code = {loc["name"]: loc["code"] for loc in locations}

    weapon_boss_codes = {
        name_to_code[name]
        for name in WEAPON_BOSS_NAMES
        if name in name_to_code
    }

    return {
        "dead_codes": sorted(_parse_frozenset(init_text, "_FREE_ROAM_DEAD_LOCATION_CODES")),
        "fort_condor_codes": sorted(_parse_frozenset(init_text, "_FORT_CONDOR_CHECK_CODES")),
        "weapon_boss_codes": sorted(weapon_boss_codes),
        "gold_saucer_regions": list(GOLD_SAUCER_REGIONS),
    }


def write_logic_seed_lua(path: Path, constants: dict[str, object], location_meta: dict[int, dict[str, str]]) -> None:
    lines = [
        "-- Generated by tools/generate_pack.py",
        "",
        "DEAD_CODES = {",
    ]
    for code in constants["dead_codes"]:
        lines.append(f"    [{code}] = true,")
    lines.extend(["}", "", "FORT_CONDOR_CODES = {"])
    for code in constants["fort_condor_codes"]:
        lines.append(f"    [{code}] = true,")
    lines.extend(["}", "", "WEAPON_BOSS_CODES = {"])
    for code in constants["weapon_boss_codes"]:
        lines.append(f"    [{code}] = true,")
    lines.extend(["}", "", "GOLD_SAUCER_REGIONS = {"])
    for region in constants["gold_saucer_regions"]:
        lines.append(f"    [{region!r}] = true,")
    lines.extend(["}", "", "LOCATION_META = {"])
    for code in sorted(location_meta):
        meta = location_meta[code]
        lines.append(f"    [{code}] = {{ region = {meta['region']!r} }},")
    lines.append("}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_logic_pool_lua(path: Path, location_codes: list[int]) -> None:
    lines = [
        "-- Generated by tools/generate_pack.py",
        "",
    ]
    for code in location_codes:
        lines.append(f"function ff7_pool_{code}()")
        lines.append(f"    return ff7_location_in_pool({code}) and 1 or 0")
        lines.append("end")
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
